[package]
name = "tui-jan"
version = "0.1.0"
description = "A Terminal UI for browsing CVEs"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
nvd_cve = { path = "../nvd_cve/" }
ratatui = "0.26.0"
crossterm = "0.27.0"
thiserror = "1.0.58"
textwrap = "0.16.1"
tui-input = "0.8.0"
tui-popup = "0.2.4"
clap = { version = "4.5.4", features = ["derive", "env", "wrap_help", "cargo"] }
